### ISSUE TITLE
Tried to listen to a value exposed with provider, from outside of the widget tree

### ISSUE THREAD

**Issue by bradyt** [bradyt/cone#54]
Tried to run `flutter run --flavor=dev`, and got the following error.

In the file `cone_android/pubspec.lock`, provider is at `3.0.0+1`.

<details>
<p>

```
I/flutter (23594): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (23594): The following assertion was thrown while handling a gesture:
I/flutter (23594): Tried to listen to a value exposed with provider, from outside of the widget tree.
I/flutter (23594):                                                      
I/flutter (23594): This is likely caused by an event handler (like a button's onPressed) that called
I/flutter (23594): Provider.of without passing `listen: false`.         
I/flutter (23594):                                                      
I/flutter (23594): To fix, write:                                       
I/flutter (23594): Provider.of<ConeModel>(context, listen: false);      
I/flutter (23594):                                                      
I/flutter (23594): It is unsupported because may pointlessly rebuild the widget associated to the
I/flutter (23594): event handler, when the widget tree doesn't care about the value.
I/flutter (23594): 'package:provider/src/provider.dart':                
I/flutter (23594): Failed assertion: line 213 pos 7: 'context.owner.debugBuilding || listen == false ||
I/flutter (23594): _debugIsInInheritedProviderUpdate'                   
I/flutter (23594):                                                      
I/flutter (23594): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23594): more information in this error message to help you determine and fix the underlying cause.
I/flutter (23594): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (23594):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (23594):                                                      
I/flutter (23594): When the exception was thrown, this was the stack:   
I/flutter (23594): #2      Provider.of (package:provider/src/provider.dart:213:7)
I/flutter (23594): #3      ConeModel.of (package:cone/src/model.dart:39:21)
I/flutter (23594): #4      SettingsButton.build.<anonymous closure> (package:cone/src/home.dart:259:19)
I/flutter (23594): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
I/flutter (23594): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
I/flutter (23594): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (23594): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
I/flutter (23594): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
I/flutter (23594): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
I/flutter (23594): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
I/flutter (23594): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
I/flutter (23594): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
I/flutter (23594): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter (23594): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
I/flutter (23594): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
I/flutter (23594): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (23594): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (23594): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (23594): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (23594): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (23594): #25     _invoke1 (dart:ui/hooks.dart:273:10)         
I/flutter (23594): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
I/flutter (23594): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (23594):                                                      
I/flutter (23594): Handler: "onTap"                                     
I/flutter (23594): Recognizer:                                          
I/flutter (23594):   TapGestureRecognizer#5bc33                         
I/flutter (23594): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

</p>
</details>

**Comment by bradyt** [comment]
Presumably fixed at https://github.com/bradyt/cone/commit/107daa5afacc46426cd467554be58b52cc0b09d4.
