### ISSUE TITLE
Error during flutter run, setState() or markNeedsBuild() called during build

### ISSUE THREAD

**Issue by bradyt** [bradyt/cone#9]
This error does not seem to prevent the app from functioning. But while developing, we want to use `flutter run` and hot reload.

This error was introduced when adding the "settings" functionality, for changing the default currency, etc.

<details><summary>log</summary>

```
Restarted application in 3,265ms.
I/flutter (18676): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (18676): The following assertion was thrown while dispatching notifications for SettingsModel:
I/flutter (18676): setState() or markNeedsBuild() called during build.
I/flutter (18676): This ChangeNotifierProvider<SettingsModel> widget cannot be marked as needing to build because the
I/flutter (18676): framework is already in the process of building widgets. A widget can be marked as needing to be
I/flutter (18676): built during the build phase only if one of its ancestors is currently building. This exception is
I/flutter (18676): allowed because the framework builds parent widgets before children, which means a dirty descendant
I/flutter (18676): will always be built. Otherwise, the framework might not visit this widget during this build phase.
I/flutter (18676): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (18676):   ChangeNotifierProvider<SettingsModel>(state: _DelegateWidgetState#f3ab8)
I/flutter (18676): The widget which was currently being built when the offending call was made was:
I/flutter (18676):   Builder
I/flutter (18676): 
I/flutter (18676): When the exception was thrown, this was the stack:
I/flutter (18676): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3503:11)
I/flutter (18676): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3529:6)
I/flutter (18676): #2      State.setState (package:flutter/src/widgets/framework.dart:1133:14)
I/flutter (18676): #3      __BuilderListenableDelegate&BuilderStateDelegate&_ListenableDelegateMixin.startListening.<anonymous closure> (package:provider/src/listenable_provider.dart:134:36)
I/flutter (18676): #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter (18676): #5      SettingsModel.defaultCurrency (package:cone/src/flutter/settings_model.dart:21:7)
I/flutter (18676): #6      AddTransactionState.initState (package:cone/src/flutter/add_transaction.dart:40:60)
I/flutter (18676): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
I/flutter (18676): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (18676): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (18676): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (18676): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (18676): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (18676): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (18676): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (18676): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (18676): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (18676): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (18676): #100    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
I/flutter (18676): #101    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (18676): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #103    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
I/flutter (18676): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (18676): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #111    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (18676): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (18676): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (18676): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (18676): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (18676): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (18676): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (18676): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (18676): #125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (18676): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (18676): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (18676): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (18676): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (18676): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (18676): #134    _invoke (dart:ui/hooks.dart:219:10)
I/flutter (18676): #135    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (18676): (elided 3 frames from package dart:async)
I/flutter (18676): 
I/flutter (18676): The SettingsModel sending notification was:
I/flutter (18676):   Instance of 'SettingsModel'
I/flutter (18676): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (18676): Another exception was thrown: setState() or markNeedsBuild() called during build.
I/flutter (18676): Another exception was thrown: setState() or markNeedsBuild() called during build.
```

</details>

**Comment by bradyt** [comment]
Fixed at 80d6c830ae8c0d007fb6f7a265f632bb80a36c55.

Thanks again to Randal L. Schwartz!
